### ISSUE TITLE
### 🔁 [DevOps] Thiết lập CI/CD pipeline với GitHub Actions cho MovieNest

### ISSUE THREAD

**Issue by phihungvo** [phihungvo/MovieNest#20]
#### 📌 Mô tả
Hiện tại dự án MovieNest chưa có quy trình kiểm thử và build tự động sau mỗi lần push hoặc pull request. Cần thiết lập **CI/CD pipeline** sử dụng **GitHub Actions** để:
- Tự động build backend & frontend.
- Chạy unit test (Java + React).
- Đảm bảo code luôn ở trạng thái hoạt động tốt trước khi merge.

#### 🎯 Mục tiêu
- Tự động hóa quy trình kiểm thử và build khi push lên `main`, `dev`, hoặc tạo PR.
- Ngăn chặn việc merge code lỗi hoặc không qua test.
- Chuẩn bị nền tảng để triển khai tự động (CD) về sau.

##### GitHub Actions (CI)
- [ ] Tạo file `.github/workflows/ci.yml`
- [ ] Thiết lập bước checkout code.
- [ ] Cài đặt môi trường Java 21 và chạy lệnh `mvn test` cho backend.
- [ ] Cài đặt môi trường Node.js (React) và chạy `npm install`, `npm run build`.
- [ ] Định nghĩa trigger khi push lên `main`, `dev`, hoặc khi tạo PR.

##### Optional (CD)
- [ ] Chuẩn bị sẵn các bước deploy thủ công (nếu dùng server riêng hoặc Vercel/Render).
- [ ] Có thể thêm job upload file lên VPS hoặc trigger webhook nếu có.

##### Backend (Spring Boot)
- [ ] Đảm bảo `pom.xml` có thể chạy `mvn clean test` thành công không lỗi.

##### Frontend (React)
- [ ] Kiểm tra lệnh `npm run build` hoạt động đúng với cấu hình hiện tại.

#### 🧠 Gợi ý kỹ thuật
Ví dụ CI pipeline:
```yaml
name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean install -DskipTests=false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
```

📅 Ước tính thời gian
- Thiết lập CI: 0.5 – 1 ngày
- Kiểm thử hoạt động: 1 – 2 giờ

🔗 Liên kết liên quan
- .github/workflows/
- Backend: pom.xml
- Frontend: package.json
